language: python
os: linux
dist: bionic

notifications:
  email: false

addons:
  apt:
    packages:
      - libhdf5-serial-dev

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/.cache/hdf5
    - $HOME/.ccache  # https://github.com/travis-ci/travis-ci/issues/5853

env:
  global:
    - HDF5_CACHE_DIR=$HOME/.cache/hdf5
    - TERM=dumb

jobs:
  include:
    # needed to work around https://github.com/travis-ci/travis-ci/issues/4794
    # TODO: We should see if we can replace this with installing python via pyenv # based on toxenv
    # Test on ppc64le
    - arch: ppc64le
      python: 3.9
      env:
      - TOXENV=py39-test-deps
      - HDF5_VERSION=1.10.5
      - HDF5_DIR=$HDF5_CACHE_DIR/$HDF5_VERSION
      - H5PY_ENFORCE_COVERAGE=yes
    - arch: arm64
      services: docker
      python: 3.9
      virt: vm
      env:
        - TOXENV=py39-test-deps
        - HDF5_VERSION=1.10.5
        - HDF5_DIR=$HDF5_CACHE_DIR/$HDF5_VERSION
        - H5PY_ENFORCE_COVERAGE=yes
        - CIBW_BUILD: cp3{8,9,10,11}-manylinux*
        - CIBW_MANYLINUX_AARCH64_IMAGE: ghcr.io/h5py/manylinux2014_aarch64-hdf5
        - CIBW_ARCHS: aarch64
before_install:
  # - export PATH=/usr/lib/ccache:$PATH
  - ccache -s

install:
    - pip install -U pip tox codecov virtualenv
    - ci/get_hdf5_if_needed.sh
    - if [[ $CIBW_ARCHS == aarch64 ]]; then python -m pip install cibuildwheel; fi

script:
    - if [[ $CIBW_ARCHS == aarch64 ]]; then python3 -m cibuildwheel --output-dir wheelhouse; fi
    - if [[ -z "$CIBW_ARCHS" ]]; then python3 -m pip install setuptools==59.2.0 wheel==0.38.1 Cython; fi
    - echo "$TERM"
    - if [[ -z "$CIBW_ARCHS" ]]; then python3 -m pip install -v --upgrade numpy | cat ; fi
    - - if [[ -z "$CIBW_ARCHS" ]]; then ci/test-build-numpy.sh; fi
    #- tox run -v
    - sleep 5

after_success:
    - python ci/upload_coverage.py

deploy:
  # Upload to GitHub releases on tag. Token is in secret environment vars in
  # Travis settings.
  provider: releases
  file: wheelhouse/h5py-*.whl
  file_glob: true
  edge: true # opt in to dpl v2
  on:
    tags: true
